Aleksandar-MessageSendingService
sedc-codecademy/sp2023-cp02-dsw-5 pull request #18
Opened 2023-11-28 08:24 UTC by Aleksandar1105

2023-11-28 19:34 UTC, KristijanJankuloski requested changes

2023-11-28 19:34 UTC, KristijanJankuloski commented on Shipfinity.Domain/Models/Message.cs
> +        public string FirstName { get; set; }
Add restrictions

2023-11-28 19:34 UTC, KristijanJankuloski commented on Shipfinity.DataAccess/Repositories/Interfaces/IMessageRepository.cs
> +        Task<Message> CreateMessageAsync(Message message);
Move this to Insert Async

2023-11-28 19:34 UTC, KristijanJankuloski commented on Shipfinity.Domain/Models/Message.cs
> +        public int Id { get; set; }
Remove id

2023-11-28 19:34 UTC, KristijanJankuloski commented on Shipfinity.Api/Controllers/MessageController.cs
> +            if(!ModelState.IsValid)
Wrap in try catch

2023-11-28 20:20 UTC, KristijanJankuloski commented
Revert changes to csproj file to resolve merge conflict

2023-11-28 22:25 UTC, cheppymk approved these changes

2023-11-29 01:47 UTC, KristijanJankuloski approved these changes

2023-11-29 01:47 UTC, merged