create reset password for seller
sedc-codecademy/sp2023-cp02-dsw-5 pull request #23
Opened 2023-11-30 21:47 UTC by cheppymk

2023-12-01 13:34 UTC, KristijanJankuloski requested changes

2023-12-01 13:34 UTC, KristijanJankuloski commented on Shipfinity.Api/appsettings.json
> +    "ShipfinityDbString": "Data Source=(localdb)\\LocalDBDemo;Database=ShipfinityDbTest;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=Rea
Revert changes to appsettings

2023-12-01 13:34 UTC, KristijanJankuloski commented on Shipfinity.Api/Controllers/SellerController.cs
> +        public async Task<IActionResult> ResetPassword(int sellerId, string oldPassword, string newPassword, string confirmNewPassword)
Move all input parameters in a dto and get them from the body

2023-12-01 13:34 UTC, KristijanJankuloski commented on Shipfinity.Services/Implementations/SellerService.cs
> +                throw new Exception("New password and confirmation do not match.");
Dont throw a generic exception here, create a new BadRequestException in the shared or domain project and throw and catch that instead, catch a generic exception at the end and return a 500 internal server error

2023-12-02 14:18 UTC, KristijanJankuloski approved these changes

2023-12-02 17:09 UTC, Aleksandar1105 approved these changes

2023-12-02 17:14 UTC, merged